export const FOOTER_KIND_DEFAULT = 'default';
export const FOOTER_KIND_SMALL = 'small';

export const FOOTER_KINDS = [FOOTER_KIND_DEFAULT, FOOTER_KIND_SMALL];

export const mutations = {
  UPDATE_FOOTER_KIND: 'UPDATE_FOOTER_KIND',
  QUIZ_UPDATE_MODEL: 'QUIZ_UPDATE_MODEL',
  QUIZ_UPDATE_HISTORY: 'QUIZ_UPDATE_HISTORY',
  QUIZ_TOOGLE_STEP_VALIDITY: 'QUIZ_TOOGLE_STEP_VALIDITY',
  SET_QUIZ_ID: 'SET_QUIZ_ID',
};

export const actions = {
  QUIZ_SEND_RESULT: 'QUIZ_SEND_RESULT', 
};
